# Simple workflow for deploying static content to GitHub Pages
name: Run tests for CI example

on:
  push:
    paths:
      - ci_example/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  # Single deploy job since we're just deploying
  test:
    runs-on: ubuntu-latest
    env:
      PYTEST_RUN_PATH: ci_example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pytest plugin
        run: pip install pytest pytest-github-actions-annotate-failures
      - name: Run tests
        run: |-
          cd ci_example
          pytest .

